[package]
name = "advent15"
description = "Solutions for Advent of Code 2015."
version = "0.1.0"
authors = ["Georg Brandl <georg@python.org>"]
edition = "2018"

[[bench]]
name = "days"
harness = false

[dependencies]
advtools = { version = "0.4.0", path = "../advtools" }
rand = "0.6.1"
itoa = "0.4.3"
md-5 = "0.8.0"
serde_json = "1.0.33"
permutohedron = "0.2.4"

[dev-dependencies]
criterion = { version = "0.2.5", default-features = false }
